### ISSUE TITLE
GitHub action for conda 

### ISSUE THREAD

**Issue by sosiristseng** [sosiristseng/sosiristseng.github.io#126]
Related to #102 #103 

```yml
- name: Setup conda
  uses: conda-incubator/setup-miniconda@v2
  with:
    installer-url: https://github.com/conda-forge/miniforge/releases/download/4.9.2-2/Mambaforge-Linux-x86_64.sh
    channel-priority: true
    use-only-tar-bz2: true
    activate-environment: my-env

- name: Install Dependencies
  run: mamba env update -f env.yml
```
