### ISSUE TITLE
Parallel matrix build on Gitlab

### ISSUE THREAD

**Issue by sosiristseng** [sosiristseng/sosiristseng.github.io#174]
https://gitlab.com/gitlab-org/gitlab/-/issues/23405#note_490693914

```yaml
test:
  image: $IMAGE
  script:
    - python -V
  parallel:
    matrix:
      - IMAGE: ['python:3.6-alpine', 'python:3.7-alpine']
```
