### ISSUE TITLE
Kodiak automerge

### ISSUE THREAD

**Issue by sosiristseng** [sosiristseng/sosiristseng.github.io#223]
https://kodiakhq.com/docs/config-reference

**Comment by sosiristseng** [comment]
## Dependabot

(Integrated with GitHub)

```yml
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
    - "automerge"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
    - "automerge"
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
    - "automerge"
```
