### ISSUE TITLE
Caching in GitLab CI/CD

### ISSUE THREAD

**Issue by sosiristseng** [sosiristseng/sosiristseng.github.io#24]
## Conda

```yml
image: condaforge/miniforge3:latest

variables:
  CONDA_PKGS_DIRS: "${CI_PROJECT_DIR}/.cache/conda/pkgs"

cache:
  - key:
      files:
        - environment.yml
    paths:
      - .env/
      - .cache/conda/pkgs

before_script:
  - conda env update --prefix ./.env --file environment.yml --prune
  - source activate ./.env
```
