### ISSUE TITLE
Hexo pandoc renderer citations

### ISSUE THREAD

**Issue by sosiristseng** [sosiristseng/sosiristseng.github.io#269]
Requires:
- `hexo-renderer-pandoc`
- `pandoc`
- `pandoc-citeproc`

config

```yml
pandoc:
  filters:
    - pandoc-citeproc
  extra:
    - bibliography: "/path/to/bibfile.bib"
```
