### ISSUE TITLE
Status check for a multi-stage workflow

### ISSUE THREAD

**Issue by sosiristseng** [sosiristseng/sosiristseng.github.io#27]
I can use the `${{ needs.<job>.result }}` variable without setting output flags.

```yaml
  # CI conclusion for GitHub status check
  # Adaped from https://brunoscheufler.com/blog/2022-04-09-the-required-github-status-check-that-wasnt
  CI:
    needs: render
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ ${{ needs.render.result }} == "success" ]]; then
            echo "Tests passed"
            exit 0
          else
            echo "Tests failed"
            exit 1
          fi
```
