### ISSUE TITLE
Tip: use Julia as custom shell in GitHub Actions 

### ISSUE THREAD

**Issue by sosiristseng** [sosiristseng/sosiristseng.github.io#294]
https://discourse.julialang.org/t/tip-use-julia-as-custom-shell-in-github-actions/53377

```yml
      - name: Install extra dependency on main branch
        shell: julia --color=yes --project=. {0}
        run: |
          using Pkg
          Pkg.add(PackageSpec(; name="AnExtraPackage", rev="main"))
```
