### ISSUE TITLE
Create MR on GitLab

### ISSUE THREAD

**Issue by sosiristseng** [sosiristseng/sosiristseng.github.io#4]
From: https://thacoon.com/posts/gitlab-ci-auto-dependency-update/

```yml
# .gitlab-ci.yml
bot:
  # only run if this is a scheduled pipeline
  only:
    - schedules

  image: python:3.8

  script:
    - cd $CI_PROJECT_DIR
    # Checkout to a new branch so we push the changes to a new branch
    - git checkout -b auto-update-$(date '+%Y-%m-%d')
    - apt-get install -qy curl
    # We are using pip-tools to handle/pin our dependencies
    - pip install pip-tools
    - chmod 700 update.sh
    # This script updates my requirements file.
    # This can be customized however you want to fit your needs.
    - ./update.sh
    # If any line was changed then commit the changes, push them and create a merge request
    - |
      lines=$(git status -s | wc -l)
      if [ $lines -gt 0 ];then
        echo "committing"
        git config --global user.name "${AUTO_COMMITTER_NAME}"
        git config --global user.email "${AUTO_COMMITTER_EMAIL}"
        git add .
        git commit -m "auto-update-$(date '+%Y-%m-%d')"
        git push "https://${GITLAB_USER_NAME}:${GIT_PUSH_TOKEN}@${CI_REPOSITORY_URL#*@}"
        BODY="{\"id\": \"${CI_PROJECT_ID}\", \"source_branch\": \"auto-update-$(date '+%Y-%m-%d')\", \"target_branch\": \"master\", \"remove_source_branch\": true, \"title\": \"Auto Update $(date '+%Y-%m-%d')\"}"
        curl -X POST "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/merge_requests" \
                --header "PRIVATE-TOKEN:${GIT_PUSH_TOKEN}" \
                --header "Content-Type: application/json" \
                --data "${BODY}";
        echo "Opened a new merge request: \"Auto Update $(date '+%Y-%m-%d')\" and assigned to you";
        exit;
      else
        echo "no change, nothing to commit"
      fi

test:
  stage: test

  # dont run if this is a scheduled pipeline
  except:
    - schedules
```
