### ISSUE TITLE
Make PR and automerge

### ISSUE THREAD

**Issue by sosiristseng** [sosiristseng/sosiristseng.github.io#7]
Create PR action: https://github.com/peter-evans/create-pull-request/

How to automerge:

- Use SSH deploy keys:<https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#push-using-ssh-deploy-keys>
- Run the auto-merge actions periodically to workaround `GITHUB_TOKEN` restrictions. From this issue thread: <https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-564110170>

```yml
name: automerge
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: rebase
          UPDATE_METHOD: rebase
```
