### ISSUE TITLE
Mamba installer

### ISSUE THREAD

**Issue by sosiristseng** [sosiristseng/sosiristseng.github.io#72]
Update Conda installation script.

**Comment by sosiristseng** [comment]
https://github.com/mamba-org/mamba

**Comment by sosiristseng** [comment]
GitHub action

```yml
- name: Setup conda
  uses: conda-incubator/setup-miniconda@v2
  with:
    installer-url: https://github.com/conda-forge/miniforge/releases/download/4.9.2-2/Mambaforge-Linux-x86_64.sh
    channel-priority: true
    use-only-tar-bz2: true
    activate-environment: my-env

- name: Anaconda Login
  run: |
    # Bypass the installation of anaconda-client
    TOKEN_DIR="$HOME/.config/binstar"
    TOKEN_PATH="$TOKEN_DIR/https%3A%2F%2Fapi.anaconda.org.token"
    mkdir -p $TOKEN_DIR
    echo -e "${ANACONDA_USER_TOKEN}\c" > $TOKEN_PATH

- name: Install Dependencies
  run: mamba env update -f env.yml
```
